# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
jobs:
  deploy:
    if: github.repository == 'afrid18/Stone'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: install Vercel CLI
        run: npm install --global vercel@latest
      - run: npm install --immutable
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
